apiVersion: v1
kind: Service
metadata:
  name: kube-web-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: kube-web-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32001
      protocol: TCP